# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-b1f76417-1330-464e-8113-fc9598a049c5";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };

  boot.initrd.luks.devices."luks-b1f76417-1330-464e-8113-fc9598a049c5".device = "/dev/disk/by-uuid/b1f76417-1330-464e-8113-fc9598a049c5";

  fileSystems."/home" =
    { device = "/dev/mapper/luks-b1f76417-1330-464e-8113-fc9598a049c5";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/BD06-A3DF";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  # Disk swap is overflow behind zram (zram is prio 5, used first). Encrypt it
  # with a fresh random key each boot so memory pages spilled here can never be
  # recovered from the powered-off disk — matches the LUKS FDE threat model.
  # Referenced by PARTUUID (stable) rather than the swap UUID, which random
  # encryption rewrites on every boot. NOTE: this precludes hibernation; if you
  # ever want resume-from-disk, switch to a keyed LUKS swap instead.
  swapDevices =
    [ { device = "/dev/disk/by-partuuid/f102c6a0-5d60-4337-bb3b-324fab38d499";
        randomEncryption.enable = true;
      }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
